// ignore_for_file: prefer_const_constructors
class Diseases{
  final int index;
  final String name;
  final List <String> precautions;
  final List <String> symptoms;
  final String description;

  Diseases({required this.index, required this.name, required this.precautions, required this.symptoms, required this.description});
}

class Resources {
  static List <Diseases> diseaseFullList = [
    Diseases(index:0, name:'Drug Reaction', precautions:['stop irritation', 'consult nearest hospital', 'stop taking drug', 'follow up'], symptoms:['skin rash', 'itching', 'stomach pain', 'burning micturition', 'spotting  urination'], description:'A drug reaction happens when two or more medicines, or something you eat or drink, do not mix well together. Sometimes, if you are not feeling well and you take a medicine without checking, it can make things worse. Like if you have high blood pressure and you take a nasal spray, it might not be good for you. So, it is important to be careful with medicines and what you consume, especially if you have health issues.'),
    Diseases(index:1, name:'Malaria', precautions:['Consult nearest hospital', 'avoid oily food', 'avoid non veg food', 'keep mosquitos out'], symptoms:['vomiting', 'chills', 'high fever', 'sweating', 'headache', 'nausea', 'diarrhoea', 'muscle pain'], description:'Malaria is a severe sickness that can sometimes lead to death. It is caused by a tiny creature called a parasite, and it usually spreads through a particular kind of mosquito that bites people. When someone gets malaria, they often become very unwell, experiencing high fevers, shivering fits, and symptoms similar to the flu.'),
    Diseases(index:2, name:'Allergy', precautions:['apply calamine', 'cover area with bandage', 'use ice to compress itching'], symptoms:['continuous sneezing', 'shivering', 'chills', 'watering from eyes'], description:'An allergy occurs when your body responds to something that is usually not harmful, such as pollen, dust, or animal fur. The symptoms can range from mild to severe, and in some cases, they can be extremely serious.'),
    Diseases(index:3, name:'Hypothyroidism', precautions:['reduce stress', 'exercise', 'eat healthy', 'get proper sleep'], symptoms:['fatigue', 'weight gain', 'cold hands and feets', 'mood swings', 'lethargy', 'dizziness', 'puffy face and eyes', 'enlarged thyroid', 'brittle nails', 'swollen extremeties', 'depression', 'irritability', 'abnormal menstruation'], description:'Hypothyroidism is a common health issue when your thyroid gland does not produce and release enough thyroid hormone into your body. This can cause your metabolism to slow down. It is also known as an underactive thyroid. When you have hypothyroidism, you might feel tired, gain weight, and have trouble handling cold weather.'),
    Diseases(index:4, name:'Psoriasis', precautions:['wash hands with warm soapy water', 'stop bleeding using pressure', 'consult doctor', 'salt baths'], symptoms:['skin rash', 'joint pain', 'skin peeling', 'silver like dusting', 'small dents in nails', 'inflammatory nails'], description:'Psoriasis is a lasting health condition where the immune system becomes too active, leading to rapid growth of skin cells. This causes scaly and red patches on the skin, often seen on the scalp, elbows, or knees, but it can occur on other body parts too.'),
    Diseases(index:5, name:'GERD', precautions:['avoid fatty spicy food', 'avoid lying down after eating', 'maintain healthy weight', 'exercise'], symptoms:['stomach pain', 'acidity', 'ulcers on tongue', 'vomiting', 'cough', 'chest pain'], description:'Gastroesophageal reflux disease (GERD) happens when stomach acid frequently goes back into the tube connecting your mouth and stomach, called the esophagus. This acid reflux can irritate the lining of the esophagus. Many people occasionally experience acid reflux.'),
    Diseases(index:6, name:'Chronic cholestasis', precautions:['cold baths', 'anti itch medicine', 'consult doctor', 'eat healthy'], symptoms:['vomiting', 'itching', 'yellowish skin', 'nausea', 'loss of appetite', 'abdominal pain', 'yellowing of eyes'], description:'Chronic cholestatic diseases, whether they start in infancy, childhood, or adulthood, are marked by problems in moving bile acids from the liver to the intestine. This issue usually arises due to damage to the biliary epithelium, primarily.'),
    Diseases(index:7, name:'hepatitis A', precautions:['Consult nearest hospital', 'wash hands through', 'avoid fatty spicy food', 'medication'], symptoms:['joint pain', 'vomiting', 'yellowish skin', 'dark urine', 'nausea', 'loss of appetite', 'abdominal pain', 'diarrhoea', 'mild fever', 'yellowing of eyes', 'muscle pain'], description:'Hepatitis A is a liver inflammation that can range from mild to severe. It is caused by the hepatitis A virus (HAV), which spreads through contaminated food and water or by close contact with an infected person. Most people recover completely from hepatitis A and become immune for life.'),
    Diseases(index:8, name:'Osteoarthristis', precautions:['acetaminophen', 'consult nearest hospital', 'follow up', 'salt baths'], symptoms:['joint pain', 'neck pain', 'knee pain', 'hip joint pain', 'swelling joints', 'painful walking'], description:'Osteoarthritis is a progressive condition that gets worse as time goes on, leading to ongoing pain. The pain and stiffness in the joints can become so severe that it makes everyday activities hard to do. This discomfort and disability can also lead to feelings of depression and sleep problems.'),
    Diseases(index:9, name:'(vertigo) Paroymsal  Positional Vertigo', precautions:['lie down', 'avoid sudden change in body', 'avoid abrupt head movment', 'relax'], symptoms:['vomiting', 'headache', 'nausea', 'spinning movements', 'loss of balance', 'unsteadiness'], description:'Benign paroxysmal positional vertigo (BPPV) is a common reason for feeling like you are spinning or that the world around you is spinning suddenly. BPPV leads to short episodes of mild to strong dizziness, usually brought on by certain movements of your head.'),
    Diseases(index:10, name:'Hypoglycemia', precautions:['lie down on side', 'check in pulse', 'drink sugary drinks', 'consult doctor'], symptoms:['vomiting', 'fatigue', 'anxiety', 'sweating', 'headache', 'nausea', 'blurred and distorted vision', 'excessive hunger', 'drying and tingling lips', 'slurred speech', 'irritability', 'palpitations'], description:'Hypoglycemia happens when your blood sugar (glucose) level drops too low for your body to function properly. This can occur for various reasons, with the most common cause being a side effect of medications used to manage diabetes.'),
    Diseases(index:11, name:'Acne', precautions:['bath twice', 'avoid fatty spicy food', 'drink plenty of water', 'avoid too many products'], symptoms:['skin rash', 'pus filled pimples', 'blackheads', 'scurring'], description:'Acne is a skin problem that happens when your hair follicles get clogged with oil and dead skin cells. This can lead to whiteheads, blackheads, or pimples. Acne is most common in teenagers, but it can affect people of any age.'),
    Diseases(index:12, name:'Diabetes ', precautions:['have balanced diet', 'exercise', 'consult doctor', 'follow up'], symptoms:['fatigue', 'weight loss', 'restlessness', 'lethargy', 'irregular sugar level', 'blurred and distorted vision', 'obesity', 'excessive hunger', 'increased appetite', 'polyuria'], description:'In diabetes, your body does not produce sufficient insulin or cannot use it effectively. When there is not enough insulin or when cells do not respond to it properly, too much sugar remains in your blood. This can lead to severe health issues over time, including heart disease, vision problems, and kidney disease.'),
    Diseases(index:13, name:'Impetigo', precautions:['soak affected area in warm water', 'use antibiotics', 'remove scabs with wet compressed cloth', 'consult doctor'], symptoms:['skin rash', 'high fever', 'blister', 'red sore around nose', 'yellow crust ooze'], description:'Impetigo begins as a red and itchy sore. As it gets better, a crusty scab that is yellow or honey-colored forms over the sore. Impetigo is typically a minor infection that can happen on any part of the body but is most common on exposed skin, like around the nose and mouth.'),
    Diseases(index:14, name:'Hypertension ', precautions:['meditation', 'salt baths', 'reduce stress', 'get proper sleep'], symptoms:['chest pain', 'headache', 'dizziness', 'loss of balance', 'lack of concentration'], description:'Hypertension, also called high blood pressure, is when the blood vessels have consistently high pressure as they carry blood from the heart to the rest of the body.'),
    Diseases(index:15, name:'Peptic ulcer diseae', precautions:['avoid fatty spicy food', 'consume probiotic food', 'eliminate milk', 'limit alcohol'], symptoms:['vomiting', 'indigestion', 'loss of appetite', 'abdominal pain', 'passage of gases', 'internal itching'], description:'Peptic ulcers are open sores that form on the inner lining of your stomach and the upper part of your small intestine. The main symptom of a peptic ulcer is stomach pain. There are different types, including gastric ulcers that happen inside the stomach.'),
    Diseases(index:16, name:'Dimorphic hemmorhoids(piles)', precautions:['avoid fatty spicy food', 'consume witch hazel', 'warm bath with epsom salt', 'consume alovera juice'], symptoms:['pain during bowel movements', 'constipation', 'pain in anal region', 'bloody stool', 'irritation in anus'], description:'Hemorrhoids, also known as piles, are swollen veins that can develop inside your rectum or outside your anus. They typically resolve on their own without needing medical treatment.'),
    Diseases(index:17, name:'Common Cold', precautions:['drink vitamin c rich drinks', 'take vapour', 'avoid cold food', 'keep fever in check'], symptoms:['continuous sneezing', 'chills', 'fatigue', 'cough', 'high fever', 'headache', 'swelled lymph nodes', 'malaise', 'phlegm', 'throat irritation', 'redness of eyes', 'sinus pressure', 'runny nose', 'congestion', 'chest pain', 'loss of smell', 'muscle pain'], description:'Common symptoms of a cold include a blocked or runny nose, sneezing, coughing, and a sore throat. Sometimes, a cold may also come with a slight fever, fatigue, a headache, and joint discomfort. People may sometimes confuse a cold with the flu, but flu symptoms are generally more severe.'),
    Diseases(index:18, name:'Chicken pox', precautions:['use neem in bathing ', 'consume neem leaves', 'take vaccine', 'avoid public places'], symptoms:['skin rash', 'itching', 'fatigue', 'lethargy', 'high fever', 'headache', 'loss of appetite', 'mild fever', 'swelled lymph nodes', 'malaise', 'red spots over body'], description:'Chickenpox is a very contagious illness caused by the varicella-zoster virus (VZV). It can lead to an itchy rash that looks like blisters, among other symptoms. This rash typically starts on the chest, back, and face, and then covers the entire body.'),
    Diseases(index:19, name:'Cervical spondylosis', precautions:['use heating pad or cold pack', 'exercise', 'take otc pain reliver', 'consult doctor'], symptoms:['weakness in limbs', 'back pain', 'neck pain', 'dizziness', 'loss of balance'], description:'Cervical spondylosis is a term used to describe the natural wear and tear that occurs in the spinal discs of your neck as you age. This process causes the discs to lose moisture and shrink, leading to the development of osteoarthritis signs, such as the growth of bony projections along the edges of bones, known as bone spurs.'),
    Diseases(index:20, name:'Hyperthyroidism', precautions:['eat healthy', 'massage', 'use lemon balm', 'take radioactive iodine treatment'], symptoms:['mood swings', 'fatigue', 'weight loss', 'restlessness', 'sweating', 'diarrhoea', 'fast heart rate', 'excessive hunger', 'muscle weakness', 'irritability', 'abnormal menstruation'], description:'Hyperthyroidism occurs when the thyroid gland produces an excess of thyroid hormone, also known as an overactive thyroid. This condition accelerates the body\'s metabolism, resulting in various symptoms like weight loss, hand tremors, and a fast or irregular heartbeat.'),
    Diseases(index:21, name:'Urinary tract infection', precautions:['drink plenty of water', 'increase vitamin c intake', 'drink cranberry juice', 'take probiotics'], symptoms:['burning micturition', 'bladder discomfort', 'foul smell of urine', 'continuous feel of urine'], description:'UTIs, or urinary tract infections, are frequent infections that occur when bacteria, often originating from the skin or rectum, enter the urethra and infect the urinary system. These infections can impact various parts of the urinary tract, with bladder infections (cystitis) being the most common type. Another type of UTI is a kidney infection (pyelonephritis).'),
    Diseases(index:22, name:'Varicose veins', precautions:['lie down flat and raise the leg high', 'use oinments', 'use vein compression', 'dont stand still for long'], symptoms:['fatigue', 'cramps', 'bruising', 'obesity', 'swollen legs', 'swollen blood vessels', 'prominent veins on calf'], description:'Varicose veins are swollen and enlarged veins that typically appear on the legs and feet. They can be bluish or dark purple and often look lumpy, bulging, or twisted. People with varicose veins may also experience symptoms like aching, heaviness, and discomfort in their legs.'),
    Diseases(index:23, name:'AIDS', precautions:['avoid open cuts', 'wear ppe if possible', 'consult doctor', 'follow up'], symptoms:['muscle wasting', 'patches in throat', 'high fever', 'extra marital contacts'], description:'Individuals with AIDS have severely weakened immune systems, making them susceptible to various opportunistic infections and serious illnesses. Without proper HIV treatment, people with AIDS typically have a life expectancy of about three years.'),
    Diseases(index:24, name:'Paralysis (brain hemorrhage)', precautions:['massage', 'eat healthy', 'exercise', 'consult doctor'], symptoms:['vomiting', 'headache', 'weakness of one body side', 'altered sensorium'], description:'A brain bleed (intracranial hemorrhage) is when there is bleeding in or around the brain. It can cause brain damage and be life-threatening. Symptoms may include a severe headache, nausea, vomiting, or sudden tingling, weakness, or numbness in the face, arm, or leg.'),
    Diseases(index:25, name:'Typhoid', precautions:['eat high calorie vegitables', 'antiboitic therapy', 'consult doctor', 'medication'], symptoms:['chills', 'vomiting', 'fatigue', 'high fever', 'headache', 'nausea', 'constipation', 'abdominal pain', 'diarrhoea', 'toxic look (typhos)', 'belly pain'], description:'People with typhoid fever have the bacteria in their bloodstream and intestines. Symptoms include a prolonged high fever, fatigue, headache, nausea, abdominal pain, and constipation or diarrhea. Some may develop a rash. In severe cases, it can lead to complications or even death.'),
    Diseases(index:26, name:'Hepatitis B', precautions:['consult nearest hospital', 'vaccination', 'eat healthy', 'medication'], symptoms:['fatigue', 'itching', 'lethargy', 'yellowish skin', 'dark urine', 'loss of appetite', 'abdominal pain', 'yellow urine', 'yellowing of eyes', 'malaise', 'receiving blood transfusion', 'receiving unsterile injections'], description:'Hepatitis B is a liver infection caused by the hepatitis B virus (HBV) that can lead to chronic infection, cirrhosis, liver cancer, and death. It is preventable with a vaccine. All medically stable infants weighing 2,000 grams or more are advised to get the hepatitis B vaccine within the first 24 hours after birth.'),
    Diseases(index:27, name:'Fungal infection', precautions:['bath twice', 'use detol or neem in bathing water', 'keep infected area dry', 'use clean cloths'], symptoms:['skin rash', 'itching', 'nodal skin eruptions', 'dischromic  patches'], description:'Fungal infections, known as mycosis, are illnesses triggered by fungi, including yeast and mold. These infections frequently affect the skin and nails but can also occur in various parts of the body like the mouth, throat, lungs, and urinary tract.'),
    Diseases(index:28, name:'Hepatitis C', precautions:['Consult nearest hospital', 'vaccination', 'eat healthy', 'medication'], symptoms:['fatigue', 'yellowish skin', 'nausea', 'loss of appetite', 'yellowing of eyes', 'family history'], description:'Hepatitis C is a liver inflammation caused by the hepatitis C virus. It can lead to both short-term (acute) and long-term (chronic) hepatitis, with severity ranging from mild to severe. Severe cases can result in lifelong illness, including liver cirrhosis and cancer.'),
    Diseases(index:29, name:'Migraine', precautions:['meditation', 'reduce stress', 'use poloroid glasses in sun', 'consult doctor'], symptoms:['acidity', 'indigestion', 'headache', 'blurred and distorted vision', 'excessive hunger', 'stiff neck', 'depression', 'irritability', 'visual disturbances'], description:'A migraine is a type of headache that can bring intense throbbing pain or a pulsing feeling, typically on one side of the head. It\'s often accompanied by symptoms like nausea, vomiting, and extreme sensitivity to light and sound.'),
    Diseases(index:30, name:'Bronchial Asthma', precautions:['switch to loose cloothing', 'take deep breaths', 'get away from trigger', 'seek help'], symptoms:['cough', 'fatigue', 'high fever', 'breathlessness', 'family history', 'mucoid sputum'], description:'Bronchial asthma is a long-lasting inflammatory condition of the airways, marked by increased sensitivity of the air passages and varying levels of airflow blockage.'),
    Diseases(index:31, name:'Alcoholic hepatitis', precautions:['stop alcohol consumption', 'consult doctor', 'medication', 'follow up'], symptoms:['vomiting', 'yellowish skin', 'abdominal pain', 'swelling of stomach', 'distention of abdomen', 'history of alcohol consumption', 'fluid overload'], description:'Alcoholic hepatitis is a serious condition linked to alcohol-related liver disease. It involves the rapid development of jaundice, feeling unwell, a tender and enlarged liver, and subtle signs of a systemic inflammatory response.'),
    Diseases(index:32, name:'Jaundice', precautions:['drink plenty of water', 'consume milk thistle', 'eat fruits and high fiberous food', 'medication'], symptoms:['vomiting', 'itching', 'fatigue', 'weight loss', 'high fever', 'yellowish skin', 'dark urine', 'abdominal pain'], description:'Jaundice is a condition where the skin, the whites of the eyes, and mucous membranes turn yellow due to elevated levels of bilirubin, a yellow-orange pigment found in bile. It can result from various factors, such as hepatitis, gallstones, and tumors.'),
    Diseases(index:33, name:'Hepatitis E', precautions:['stop alcohol consumption', 'rest', 'consult doctor', 'medication'], symptoms:['joint pain', 'vomiting', 'fatigue', 'high fever', 'yellowish skin', 'dark urine', 'nausea', 'loss of appetite', 'abdominal pain', 'yellowing of eyes', 'acute liver failure', 'coma', 'stomach bleeding'], description:'Hepatitis E is a liver disease caused by the hepatitis E virus (HEV). While it is uncommon in developed nations, it is prevalent in developing countries. In most cases, HEV infection leads to a short-term, acute illness that resolves on its own.'),
    Diseases(index:34, name:'Dengue', precautions:['drink papaya leaf juice', 'avoid fatty spicy food', 'keep mosquitos away', 'keep hydrated'], symptoms:['skin rash', 'chills', 'joint pain', 'vomiting', 'fatigue', 'high fever', 'headache', 'nausea', 'loss of appetite', 'pain behind the eyes', 'back pain', 'malaise', 'muscle pain', 'red spots over body'], description:'Dengue, also known as "break-bone fever," is a viral infection transmitted from mosquitoes to humans. It is more prevalent in tropical and subtropical regions. Many people infected with dengue show no symptoms, but those who do often experience high fever, headache, body aches, nausea, and a rash.'),
    Diseases(index:35, name:'Hepatitis D', precautions:['consult doctor', 'medication', 'eat healthy', 'follow up'], symptoms:['joint pain', 'vomiting', 'fatigue', 'yellowish skin', 'dark urine', 'nausea', 'loss of appetite', 'abdominal pain', 'yellowing of eyes'], description:'Hepatitis D is a viral infection that results in inflammation and harm to the liver. Inflammation is the body\'s response to injury or infection, which can lead to organ damage. Viruses invade and affect normal cells in the body.'),
    Diseases(index:36, name:'Heart attack', precautions:['call ambulance', 'chew or swallow asprin', 'keep calm'], symptoms:['vomiting', 'breathlessness', 'sweating', 'chest pain'], description:'The majority of heart attacks typically cause discomfort in the center or left side of the chest. This discomfort lasts for more than a few minutes or comes and goes. It can be described as pressure, squeezing, fullness, or pain. Other symptoms may include feeling weak, lightheaded, or dizzy, along with breaking out in a cold sweat.'),
    Diseases(index:37, name:'Pneumonia', precautions:['consult doctor', 'medication', 'rest', 'follow up'], symptoms:['chills', 'fatigue', 'cough', 'high fever', 'breathlessness', 'sweating', 'malaise', 'phlegm', 'chest pain', 'fast heart rate', 'rusty sputum'], description:'Pneumonia is an infection that causes inflammation in the air sacs (alveoli) of the lungs. These air sacs can become filled with fluid or pus, leading to symptoms like coughing, fever, chills, and difficulty breathing.'),
    Diseases(index:38, name:'Arthritis', precautions:['exercise', 'use hot and cold therapy', 'try acupuncture', 'massage'], symptoms:['muscle weakness', 'stiff neck', 'swelling joints', 'movement stiffness', 'painful walking'], description:'Arthritis refers to the swelling and tenderness of one or more joints. The primary symptoms of arthritis are pain and stiffness in the affected joints, which often get worse as a person gets older. The most common types of arthritis are osteoarthritis and rheumatoid arthritis.'),
    Diseases(index:39, name:'Gastroenteritis', precautions:['stop eating solid food for while', 'try taking small sips of water', 'rest', 'ease back into eating'], symptoms:['vomiting', 'sunken eyes', 'dehydration', 'diarrhoea'], description:'Gastroenteritis is an inflammation of the stomach and intestinal lining. Its main symptoms are vomiting and diarrhea. In healthy individuals, it is typically not a serious condition, but it can occasionally lead to dehydration or severe symptoms.'),
    Diseases(index:40, name:'Tuberculosis', precautions:['cover mouth', 'consult doctor', 'medication', 'rest'], symptoms:['vomiting', 'chills', 'fatigue', 'weight loss', 'cough', 'high fever', 'breathlessness', 'sweating', 'loss of appetite', 'mild fever', 'yellowing of eyes', 'swelled lymph nodes', 'malaise', 'phlegm', 'chest pain', 'blood in sputum'], description:'Tuberculosis (TB) is an illness caused by germs that can be transmitted from one person to another through the air. TB often impacts the lungs but can also affect other body parts like the brain, kidneys, or spine. Without treatment, TB can be fatal.'),

  ];
}


class Symptoms{
  final int index;
  final String name;

  Symptoms({required this.index, required this.name});
}

class ResourcesSymptoms{
  static List <Symptoms> symptomsFullList =[
    Symptoms(index:0, name:'itching'),
    Symptoms(index:1, name:'skin rash'),
    Symptoms(index:2, name:'nodal skin eruptions'),
    Symptoms(index:3, name:'continuous sneezing'),
    Symptoms(index:4, name:'shivering'),
    Symptoms(index:5, name:'chills'),
    Symptoms(index:6, name:'joint pain'),
    Symptoms(index:7, name:'stomach pain'),
    Symptoms(index:8, name:'acidity'),
    Symptoms(index:9, name:'ulcers on tongue'),
    Symptoms(index:10, name:'muscle wasting'),
    Symptoms(index:11, name:'vomiting'),
    Symptoms(index:12, name:'burning micturition'),
    Symptoms(index:13, name:'spotting urination'),
    Symptoms(index:14, name:'fatigue'),
    Symptoms(index:15, name:'weight gain'),
    Symptoms(index:16, name:'anxiety'),
    Symptoms(index:17, name:'cold hands and feets'),
    Symptoms(index:18, name:'mood swings'),
    Symptoms(index:19, name:'weight loss'),
    Symptoms(index:20, name:'restlessness'),
    Symptoms(index:21, name:'lethargy'),
    Symptoms(index:22, name:'patches in throat'),
    Symptoms(index:23, name:'irregular sugar level'),
    Symptoms(index:24, name:'cough'),
    Symptoms(index:25, name:'high fever'),
    Symptoms(index:26, name:'sunken eyes'),
    Symptoms(index:27, name:'breathlessness'),
    Symptoms(index:28, name:'sweating'),
    Symptoms(index:29, name:'dehydration'),
    Symptoms(index:30, name:'indigestion'),
    Symptoms(index:31, name:'headache'),
    Symptoms(index:32, name:'yellowish skin'),
    Symptoms(index:33, name:'dark urine'),
    Symptoms(index:34, name:'nausea'),
    Symptoms(index:35, name:'loss of appetite'),
    Symptoms(index:36, name:'pain behind the eyes'),
    Symptoms(index:37, name:'back pain'),
    Symptoms(index:38, name:'constipation'),
    Symptoms(index:39, name:'abdominal pain'),
    Symptoms(index:40, name:'diarrhoea'),
    Symptoms(index:41, name:'mild fever'),
    Symptoms(index:42, name:'yellow urine'),
    Symptoms(index:43, name:'yellowing of eyes'),
    Symptoms(index:44, name:'acute liver failure'),
    Symptoms(index:45, name:'fluid overload'),
    Symptoms(index:46, name:'swelling of stomach'),
    Symptoms(index:47, name:'swelled lymph nodes'),
    Symptoms(index:48, name:'malaise'),
    Symptoms(index:49, name:'blurred and distorted vision'),
    Symptoms(index:50, name:'phlegm'),
    Symptoms(index:51, name:'throat irritation'),
    Symptoms(index:52, name:'redness of eyes'),
    Symptoms(index:53, name:'sinus pressure'),
    Symptoms(index:54, name:'runny nose'),
    Symptoms(index:55, name:'congestion'),
    Symptoms(index:56, name:'chest pain'),
    Symptoms(index:57, name:'weakness in limbs'),
    Symptoms(index:58, name:'fast heart rate'),
    Symptoms(index:59, name:'pain during bowel movements'),
    Symptoms(index:60, name:'pain in anal region'),
    Symptoms(index:61, name:'bloody stool'),
    Symptoms(index:62, name:'irritation in anus'),
    Symptoms(index:63, name:'neck pain'),
    Symptoms(index:64, name:'dizziness'),
    Symptoms(index:65, name:'cramps'),
    Symptoms(index:66, name:'bruising'),
    Symptoms(index:67, name:'obesity'),
    Symptoms(index:68, name:'swollen legs'),
    Symptoms(index:69, name:'swollen blood vessels'),
    Symptoms(index:70, name:'puffy face and eyes'),
    Symptoms(index:71, name:'enlarged thyroid'),
    Symptoms(index:72, name:'brittle nails'),
    Symptoms(index:73, name:'swollen extremeties'),
    Symptoms(index:74, name:'excessive hunger'),
    Symptoms(index:75, name:'extra marital contacts'),
    Symptoms(index:76, name:'drying and tingling lips'),
    Symptoms(index:77, name:'slurred speech'),
    Symptoms(index:78, name:'knee pain'),
    Symptoms(index:79, name:'hip joint pain'),
    Symptoms(index:80, name:'muscle weakness'),
    Symptoms(index:81, name:'stiff neck'),
    Symptoms(index:82, name:'swelling joints'),
    Symptoms(index:83, name:'movement stiffness'),
    Symptoms(index:84, name:'spinning movements'),
    Symptoms(index:85, name:'loss of balance'),
    Symptoms(index:86, name:'unsteadiness'),
    Symptoms(index:87, name:'weakness of one body side'),
    Symptoms(index:88, name:'loss of smell'),
    Symptoms(index:89, name:'bladder discomfort'),
    Symptoms(index:90, name:'foul smell ofurine'),
    Symptoms(index:91, name:'continuous feel of urine'),
    Symptoms(index:92, name:'passage of gases'),
    Symptoms(index:93, name:'internal itching'),
    Symptoms(index:94, name:'toxic look (typhos)'),
    Symptoms(index:95, name:'depression'),
    Symptoms(index:96, name:'irritability'),
    Symptoms(index:97, name:'muscle pain'),
    Symptoms(index:98, name:'altered sensorium'),
    Symptoms(index:99, name:'red spots over body'),
    Symptoms(index:100, name:'belly pain'),
    Symptoms(index:101, name:'abnormal menstruation'),
    Symptoms(index:102, name:'dischromic patches'),
    Symptoms(index:103, name:'watering from eyes'),
    Symptoms(index:104, name:'increased appetite'),
    Symptoms(index:105, name:'polyuria'),
    Symptoms(index:106, name:'family history'),
    Symptoms(index:107, name:'mucoid sputum'),
    Symptoms(index:108, name:'rusty sputum'),
    Symptoms(index:109, name:'lack of concentration'),
    Symptoms(index:110, name:'visual disturbances'),
    Symptoms(index:111, name:'receiving blood transfusion'),
    Symptoms(index:112, name:'receiving unsterile injections'),
    Symptoms(index:113, name:'coma'),
    Symptoms(index:114, name:'stomach bleeding'),
    Symptoms(index:115, name:'distention of abdomen'),
    Symptoms(index:116, name:'history of alcohol consumption'),
    Symptoms(index:117, name:'fluid overload'),
    Symptoms(index:118, name:'blood in sputum'),
    Symptoms(index:119, name:'prominent veins on calf'),
    Symptoms(index:120, name:'palpitations'),
    Symptoms(index:121, name:'painful walking'),
    Symptoms(index:122, name:'pus filled pimples'),
    Symptoms(index:123, name:'blackheads'),
    Symptoms(index:124, name:'scurring'),
    Symptoms(index:125, name:'skin peeling'),
    Symptoms(index:126, name:'silver like dusting'),
    Symptoms(index:127, name:'small dents in nails'),
    Symptoms(index:128, name:'inflammatory nails'),
    Symptoms(index:129, name:'blister'),
    Symptoms(index:130, name:'red sore around nose'),
    Symptoms(index:131, name:'yellow crust ooze'),
    Symptoms(index:132, name:'prognosis'),
  ];
}
